services:
  db:
    container_name: postgres
    image: postgres:15.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: dimm
      POSTGRES_PASSWORD: cghbyu-trpfvgk
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
  dimm-api:
    container_name: dimm-api
    image: slimslk/dimm-api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8088:8080"
    networks:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
  dimm-react:
    container_name: dimm-react
    image: slimslk/dimm-react
#    build:
#      context: frontend/react
#      args:
#        api_base_url: http://localhost:8088
    restart: unless-stopped
    depends_on:
      - dimm-api
    ports:
      - "3000:5173"
networks:
  db:
    driver: bridge
volumes:
  db:



