services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
  dimm-api:
    container_name: dimm-api
    image: slimslk/dimm-api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8088:8080"
    networks:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
networks:
  db:
    driver: bridge
volumes:
  db:



